version: "3"
services:
  mysql-1:
    container_name: mysql-1
    build: ./docker/mysql
    image: javatest/mysql:1.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      driver: com.mysql.jdbc.Driver
      url: jdbc:mysql://192.168.99.100:3306/sakila
      user: root
      password: 1234

  java-1:
    container_name: java-1
    build: ./docker/java
    image: javatest/java:1.0
     ports:
          - "8080:8080"
    depends_on:
      - mysql-1
    links:
      - mysql-1
    environment:
      MYSQL_IP: mysql-1
      MYSQL_PORT: 3306