logging:
  level:
    com.hand.exam.api.controller.v1.StudentController: WARN
    com.hand.exam.infra.mapper: DEBUG
    com.hand.exam.api.service: INFO


server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sakila?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf8&autoReconnect=true&rewriteBatchedStatements=TRUE&useSSL=false&allowMultiQueries=true
    driver-class-name: com.mysql.jdbc.Driver
    password: 1234
    username: root

## mybatis
mybatis:
  mapper-locations: com.hand.exam.infra.mapper/*.xml
  type-aliases-package: com.hand.exam.domain.entity